### PR TITLE
Enable the auth middleware.

### PR DESCRIPTION
**Pull request by andy9775**
Adds the ability for the auth middleware to skip certain paths and enables it application wide,
except for user authentication paths.

### CODE REVIEW

**Review by plausibly — APPROVED** [review]
Looks good but can you test some of the routes with postman to make sure it works as intended and no minor bugs that we may have missed

**Comment by andy9775** [comment]
> Looks good but can you test some of the routes with postman to make sure it works as intended and no minor bugs that we may have missed

I make sure that the skippedRoutes are actually skipped.

**Comment by plausibly** [comment]
> > Looks good but can you test some of the routes with postman to make sure it works as intended and no minor bugs that we may have missed
> 
> I make sure that the skippedRoutes are actually skipped.



> > Looks good but can you test some of the routes with postman to make sure it works as intended and no minor bugs that we may have missed
> 
> I make sure that the skippedRoutes are actually skipped.

Check to make sure the regex matches valid URLs as well

**Comment by andy9775** [comment]
> > > Looks good but can you test some of the routes with postman to make sure it works as intended and no minor bugs that we may have missed
> > 
> > 
> > I make sure that the skippedRoutes are actually skipped.
> 
> Check to make sure the regex properly matches valid URLs as well

I did. It'll only ignore the ones specified, otherwise everything else goes through auth.

**Review by plausibly — APPROVED** [review]

**Review by danielduong8 — APPROVED** [review]

**Comment by danielduong8** [comment]
lgtm sir!

**Pull request merged**
