### PR TITLE
Set up NGINX reverse proxy

### PR DESCRIPTION
**Pull request by danielduong8**
Set up reverse proxy to API #16 

- Update nginx config to proxy all URIs that start with /api/

### CODE REVIEW

**Comment by danielduong8** [comment]
Marking this as draft until #10 is approved.

**Review by plausibly — CHANGES_REQUESTED** [review]
Deploy and test if the routes work

**Comment by danielduong8** [comment]
> Deploy and test if the routes work

Waiting on #10 to be approved and merged since it has the /api/user/ endpoint and also the signup and signin logic.

**Review by andy9775 — APPROVED** [review]
LGTM!

**Pull request merged**
